/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Freelancer as PrismaFreelancer } from "@prisma/client";

export class FreelancerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FreelancerCountArgs, "select">
  ): Promise<number> {
    return this.prisma.freelancer.count(args);
  }

  async freelancers(
    args: Prisma.FreelancerFindManyArgs
  ): Promise<PrismaFreelancer[]> {
    return this.prisma.freelancer.findMany(args);
  }
  async freelancer(
    args: Prisma.FreelancerFindUniqueArgs
  ): Promise<PrismaFreelancer | null> {
    return this.prisma.freelancer.findUnique(args);
  }
  async createFreelancer(
    args: Prisma.FreelancerCreateArgs
  ): Promise<PrismaFreelancer> {
    return this.prisma.freelancer.create(args);
  }
  async updateFreelancer(
    args: Prisma.FreelancerUpdateArgs
  ): Promise<PrismaFreelancer> {
    return this.prisma.freelancer.update(args);
  }
  async deleteFreelancer(
    args: Prisma.FreelancerDeleteArgs
  ): Promise<PrismaFreelancer> {
    return this.prisma.freelancer.delete(args);
  }
}
