/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Freelancer } from "./Freelancer";
import { FreelancerCountArgs } from "./FreelancerCountArgs";
import { FreelancerFindManyArgs } from "./FreelancerFindManyArgs";
import { FreelancerFindUniqueArgs } from "./FreelancerFindUniqueArgs";
import { DeleteFreelancerArgs } from "./DeleteFreelancerArgs";
import { FreelancerService } from "../freelancer.service";
@graphql.Resolver(() => Freelancer)
export class FreelancerResolverBase {
  constructor(protected readonly service: FreelancerService) {}

  async _freelancersMeta(
    @graphql.Args() args: FreelancerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Freelancer])
  async freelancers(
    @graphql.Args() args: FreelancerFindManyArgs
  ): Promise<Freelancer[]> {
    return this.service.freelancers(args);
  }

  @graphql.Query(() => Freelancer, { nullable: true })
  async freelancer(
    @graphql.Args() args: FreelancerFindUniqueArgs
  ): Promise<Freelancer | null> {
    const result = await this.service.freelancer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Freelancer)
  async deleteFreelancer(
    @graphql.Args() args: DeleteFreelancerArgs
  ): Promise<Freelancer | null> {
    try {
      return await this.service.deleteFreelancer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
